services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    env_file: .env
    ports: ["8000:8000"]
    command: gunicorn medicab.wsgi:application -b 0.0.0.0:8000 --workers 3
