version: "3.9"
services:
  web:
    image: ghcr.io/<ton_org>/<ton_repo>:main
    env_file: .env
    command: bash docker/entrypoint.sh
    ports: [ "8000:8000" ]
    depends_on: [ db, redis, minio, clamav ]
    restart: unless-stopped
  worker:
    image: ghcr.io/<ton_org>/<ton_repo>:main
    env_file: .env
    command: celery -A medicab worker -l INFO
    depends_on: [ db, redis, minio ]
    restart: unless-stopped
  beat:
    image: ghcr.io/<ton_org>/<ton_repo>:main
    env_file: .env
    command: celery -A medicab beat -l INFO
    depends_on: [ db, redis ]
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes: [ pgdata:/var/lib/postgresql/data ]
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ minio:/data ]
    restart: unless-stopped
  minio-setup:
    image: minio/mc
    depends_on: [ minio ]
    env_file: .env
    entrypoint: ["/bin/sh","/scripts/create_minio_buckets.sh"]
    volumes:
      - ./scripts/create_minio_buckets.sh:/scripts/create_minio_buckets.sh:ro
    restart: "no"
  clamav:
    image: clamav/clamav:stable
    ports: [ "3310:3310" ]
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    environment: [ "OLLAMA_KEEP_ALIVE=24h" ]
    volumes: [ ollama:/root/.ollama ]
    ports: [ "11434:11434" ]
    restart: unless-stopped
volumes: { pgdata: {}, minio: {}, ollama: {} }
