services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: bash -lc 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
