version: "3.9"
services:
  web:
    image: ghcr.io/dirmedical007-lgtm/medicab:main
    env_file: .env
    command: bash docker/entrypoint.sh
    ports: ["8000:8000"]
    depends_on: [db, redis]
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    image: redis:7-alpine
