services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file: .env
    ports: ["8000:8000"]
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
