FROM python:3.13.17-slim as base
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1 DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tesseract-ocr libxml2 libxslt1.1 libpango-1.0-0 libcairo2 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /app
ENV DJANGO_SETTINGS_MODULE=medicab.settings
CMD ["gunicorn","medicab.wsgi:application","-b","0.0.0.0:8000","-w","4"]
