FROM python:3.13.17-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tesseract-ocr libpango-1.0-0 libcairo2 libxml2 libxslt1.1 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /app
ENV DJANGO_SETTINGS_MODULE=medicab.settings
CMD ["gunicorn","medicab.wsgi:application","-b","0.0.0.0:8000","-w","3"]
